// Generated by CoffeeScript 1.6.3
(function() {
  var _;

  _ = require('underscore');

  module.exports = {
    dimensions: function(metric) {
      if (metric == null) {
        metric = this.get('metric');
      }
      if (metric) {
        return this.get('dimensions')[metric];
      }
    },
    superscriptFractions: function(string) {
      return string != null ? string.replace(/(\d+)(?:\s+)(\d+\/\d+)/g, '$1 <sup>$2</sup>') : void 0;
    }
  };

}).call(this);
